types:
  - deploy

ST compile and deploy:
  type: deploy
  script:
    - cd OneToolbox
    - ant clean release
    - NOW=$(date +"%Y-%m-%d_%H-%M-%S")
    - cp "OneToolbox/bin/Sense Toolbox-release.apk" "/home/toolbox/data/www/sensetoolbox.com/deploy/SenseToolbox_$NOW.apk"
